name: Rebuild and Deploy to gh-pages
on:
  push:	
    branches:	
      - main
jobs:
  deploy:
    name: Checkout and Build
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: npm install and build
      run: |
        npm ci --no-audit
        npm run build

    - name: Deploy to gh-pages
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}